### ISSUE TITLE
Produces a brief white screen when launching the latest version 1.7.3

### ISSUE THREAD

**Issue by lxmwwl** [mirnovov/obsidian-homepage#100]
### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
The blank screen is to allow Homepage to load the notes without the user seeing the old notes pop out and such, and is intended behaviour. It should only be a brief flicker though; if it takes longer than that, that isn't intended.

If you want to disable it, you can add a [CSS snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets): 

```css
.nv-homepage-interstitial {
    display: none !important;
}
```
