### ISSUE TITLE
[Feature Request] Option to configure home icon

### ISSUE THREAD

**Issue by thulasi-ram** [mirnovov/obsidian-homepage#11]
Right now the icon is hard coded into main. Requesting to provide a way to configure it or override it with snippets

**Comment by mirnovov** [comment]
I don't intend to provide a way to directly customise the icon, as this falls outside of the plugin's scope imo. However, these snippets may be good enough - you can replace the text and icon with whatever you want.

Single character:

```css
.side-dock-ribbon-action[aria-label="Open homepage"] > svg {
    display: none;
}

.side-dock-ribbon-action[aria-label="Open homepage"]:after {
    content: "🏠";
}
```

Image (of course, won't work offline):

```css
.side-dock-ribbon-action[aria-label="Open homepage"] > svg {
    display: none;
}

.side-dock-ribbon-action[aria-label="Open homepage"]:after {
    content: "";
    display: block;
    background-image: url("https://upload.wikimedia.org/wikipedia/commons/e/e5/Gnome-go-home.svg");
    background-size: contain;
    background-repeat: no-repeat;
    width: 100%;
    height: 30px;
}
```
